cyverse-de/apps

src/apps/service/apps/de/listings.clj

The UI is able to display app details with an empty "Tool Information" tab for private apps that have no tools set yet.
So this error response is obsolete.

CORE-5372 Remove “no tool” error in /apps/:id/details endpoint.

---

project.clj
src/apps/protocols.clj
src/apps/routes/apps.clj
src/apps/routes/schemas/analysis.clj
src/apps/routes/schemas/analysis/listing.clj
src/apps/routes/schemas/app.clj
src/apps/service/apps.clj
src/apps/service/apps/agave.clj
src/apps/service/apps/agave/jobs.clj
src/apps/service/apps/combined.clj
src/apps/service/apps/de.clj
src/apps/service/apps/de/constants.clj
src/apps/service/apps/de/edit.clj
src/apps/service/apps/de/job_view.clj
src/apps/service/apps/de/jobs.clj
src/apps/service/apps/de/listings.clj
src/apps/service/apps/de/pipeline_edit.clj
src/apps/service/apps/job_listings.clj
src/apps/service/apps/jobs.clj

This adds the job execution system ID, which is different from Agave's execution system iD, to several app and analysis editing and listing endpoints.

Add the execution system ID to analysis and app listing endpoints.

---

project.clj
src/apps/persistence/jobs.clj
src/apps/protocols.clj
src/apps/routes/admin.clj
src/apps/routes/schemas/app.clj
src/apps/routes/schemas/app/category.clj
src/apps/service/apps.clj
src/apps/service/apps/agave.clj
src/apps/service/apps/agave/listings.clj
src/apps/service/apps/combined.clj
src/apps/service/apps/de.clj
src/apps/service/apps/de/listings.clj
src/apps/service/util.clj

This PR adds a `job_stats` JSON object with `job_count_completed` and `job_last_completed` fields to the following endpoint responses:
* `GET /apps`
* `GET /apps/{app-id}/details`
* `GET /apps/{system-id}/{app-id}/details`
* `GET /apps/categories/{category-id}`
* `GET /apps/hierarchies/{root-iri}/apps`
* `GET /apps/hierarchies/{root-iri}/unclassified`
For example:
```json
{
"job_stats": {
"job_count_completed": 0,
"job_last_completed": "2016-10-12T00:38:57.037Z"
}
}
```
Also a `job_stats` field with the same JSON object above, but also with `job_count`, `job_count_failed`, and `last_used` fields were added to the following endpoint responses:
* `PATCH /admin/apps/{app-id}`
* `GET /admin/apps/{app-id}/details`
* `GET /admin/ontologies/{ontology-version}/{root-iri}/apps`
* `GET …

CORE-8162 Add job stats fields to app listings and details endpoints.

---

src/apps/routes/schemas/app.clj
src/apps/routes/schemas/app/category.clj
src/apps/service/apps/agave.clj
src/apps/service/apps/agave/listings.clj
src/apps/service/apps/de/listings.clj

Removes `job_stats` from non-admin app listing endpoint results, since job stat columns have been removed from the `app_listing` view by cyverse-de/de-db#2.
Admin app search and listing endpoints now use the new admin search and app listing functions added by cyverse-de/kameleon#2 so they can still include `job_stats` in their results.
Also includes a fix for adding admin `job_stats` to `apps.service.apps.agave.listings/list-apps-with-ontology` results.

CORE-8162 Remove job_stats from non-admin app listing endpoint results

---

project.clj
src/apps/persistence/jobs.clj

This PR will exclude the parent job of batch jobs in the `job_stats` counts of app details endpoint responses.

CORE-8162 Exclude parent jobs from app details `job_stats` counts.

---

project.clj
src/apps/routes/admin.clj
src/apps/routes/apps.clj
src/apps/routes/params.clj
src/apps/service/apps/combined.clj
src/apps/service/apps/combined/util.clj
src/apps/service/apps/de.clj
src/apps/service/apps/de/listings.clj

This PR updates the `GET /admin/apps` and `GET /apps` endpoints to allow their `search` params to be optional, using the new functions added by cyverse-de/kameleon#4.
This allows these endpoints to return a paged listing of all apps accessible by the requesting user if the `search` param is not provided.
Also some redundant code in `apps.service.apps.combined` was cleaned up.

CORE-8375 Allow `search` param to be optional in GET apps endpoints.

---

project.clj
src/apps/routes/admin.clj
src/apps/routes/apps.clj
src/apps/routes/apps/categories.clj
src/apps/routes/params.clj
src/apps/routes/schemas/app.clj
src/apps/routes/schemas/app/category.clj
src/apps/service/apps/agave/listings.clj
src/apps/service/apps/combined/util.clj
src/apps/service/apps/de.clj
src/apps/service/apps/de/listings.clj
src/apps/service/util.clj
test/apps/service/apps/combined_test.clj
test/apps/service/apps/permissions_test.clj
test/apps/service/apps/test_fixtures.clj

This PR introduces 2 major changes for app listing responses:
1.  Allows sorting results under the `job_stats` and `rating` fields and fixes combined app sorting for fields with number values (such as job counts).
2. Renames the `app_count` field to `total` since this is what the UI expects for paging results.
The swagger docs of the `GET /admin/apps` and `GET /apps` endpoints were also updated to enumerate their valid sort fields.
This PR also requires changes from cyverse-de/mescal#2.

CORE-8375 Fixes for apps listing endpoints.

---

project.clj
src/apps/service/apps/de/listings.clj
test/apps/service/apps/public_apps_test.clj

Updated `apps.service.apps.de.listings/list-apps` to use the new `kameleon.app-listing/count-apps-for-admin` function added by cyverse-de/kameleon#5.
This new function, along with the updated `kameleon.app-listing/get-apps-for-admin` function, allows deleted apps to be returned in the results for admins.

CORE-3957 Update GET /admin/apps to include deleted apps.

---

src/apps/routes/oauth.clj
src/apps/routes/schemas/oauth.clj
src/apps/routes/schemas/user.clj
src/apps/routes/users.clj
src/apps/service/users.clj

This PR combines user login responses for the terrain `bootstrap` endpoint, so it only needs to make 1 call to get both pieces of user "session" info.
This info wasn't combined with the apps `GET /workspaces` endpoint response, since this kind of user info will eventually be moved into a new `user-info` service, and workspaces will likely remain apps service specific.

CORE-7813 Add auth_redirect to /users/login response.

---

src/apps/containers.clj
src/apps/persistence/docker_registries.clj
src/apps/persistence/entities.clj

Since the model namespace has been updated, this gets passed the whole way to road-runner. Which, right now, doesn't actually use it. That's next, after cyverse-de/dockerops#1 can be used to do it.
Tested that everything still works properly with this (and made a few small changes to other code to ensure as much).

CORE-8455: pass docker registry auth information down to jex-adapter etc.

---

project.clj
src/apps/clients/metadata.clj
src/apps/metadata/avus.clj
src/apps/routes/admin.clj
src/apps/routes/apps.clj
src/apps/routes/apps/categories.clj
src/apps/routes/apps/metadata.clj
src/apps/routes/middleware.clj
src/apps/service/apps/de/admin.clj
src/apps/service/apps/de/categorization.clj
src/apps/service/apps/de/listings.clj
src/apps/service/apps/de/metadata.clj
src/apps/util/config.clj
test/apps/test_fixtures.clj

Updates for the new protocol version of `metadata-client` added by cyverse-de/metadata-client#1.
Includes a new `apps.clients.metadata` namespace to facade calls to `metadata-client` with common apps service parameters.

CORE-8487 Update to new protocol version of metadata-client

---

src/apps/routes/schemas/permission.clj
src/apps/service/apps/jobs/sharing.clj

The `POST /analyses/sharing` and `POST /analyses/unsharing` endpoints have been updated so that they no longer return an error when the results folder can't be (un)shared. Instead, the response will return success, but will now include an `outputs_error` field with an error message for the results (un)share error.
For example:
```json
{
"unsharing": [
{
"user": "username",
"analyses": [
{
"analysis_id": "714d5da0-e1bf-11e6-bf3b-f64e9b87c109",
"analysis_name": "Word_Count_analysis1",
"success": true,
"outputs_error": "unable to unshare result folder: ERR_DOES_NOT_EXIST"
}
]
}
]
}
```
This allows jobs to be (un)shared, even when the job has not yet completed and the output folder doesn't exist, or if the output folder has been renamed.

CORE-8540 Allow jobs without outputs to be (un)shared.

---

project.clj
src/apps/routes/apps.clj
src/apps/routes/schemas/permission.clj
src/apps/service/apps/agave.clj
src/apps/service/apps/agave/sharing.clj

These changes add support for Agave app sharing using the new features added by cyverse-de/mescal#4.
Agave app sharing is the last feature required to enable job sharing for Agave apps.

CORE-8555: Allow sharing of Agave apps and analyses

---

src/apps/service/apps/job_listings.clj
src/apps/service/apps/jobs.clj

The `can_share` flag will now only be set to `true` if the requesting user also has `own` permission for the job.
A side effect of this change is that the return values of `apps.service.apps.job-listings/list-job` and `apps.service.apps.jobs/update-job-status` will currently always have this flag set to `false`, since they do not lookup permissions, but this `can_share` flag is currently only used in the `GET /analyses` response.

CORE-8593 Update `GET /analyses` can_share flag with permission check.

---

src/apps/routes/schemas/permission.clj
src/apps/service/apps/jobs/sharing.clj

Attempting to share a job created by a "read-only" app, with a user that does not already have permissions on that app, will return an error like the following:
```json
{
"error_code": "ERR_BAD_REQUEST",
"reason": "insufficient privileges for app ID a25da189-ffe6-4f61-9a91-704711f36bd7"
}
```
This PR changes the job sharing endpoint, similar to #27, so that the app is shared after the job is successfully shared. If there is an error sharing the app, then the error message is included in a `app_error` field of the share's success response JSON:
```json
{
"sharing": [
{
"user": "username",
"analyses": [
{
"analysis_id": "14b27a4a-fd39-11e6-9a18-f64e9b87c109",
"permission": "read",
"analysis_name": "New_app_analysis1",
"success": true,
"app_error": "insufficient privileges for app ID …
```

CORE-8609 Allow sharing of jobs from read-only apps.

---

src/apps/clients/permissions.clj
src/apps/routes/schemas/tool.clj
src/apps/routes/tools.clj
src/apps/tools.clj
src/apps/util/config.clj
test/apps/service/apps/test_fixtures.clj
test/apps/tools_test.clj

This PR updates the following endpoints with public permissions support for tools (all tools are currently considered public):
* `POST /admin/tools`
* `DELETE /admin/tools/:id`
* `GET /tools`
A future PR will add support to allow users to add private tools, and to restrict tool listing and details based on private vs. public permissions. This PR is just to ensure that tool permissions stay in sync with any tools added or deleted by admins before any further features are implemented.

CORE-8418: Add permissions support for public tools

---

src/apps/service/apps/de/admin.clj
src/apps/service/apps/de/metadata.clj
src/apps/service/apps/de/validation.clj

Now that this endpoint is guarded with a `system-id`, the apps service can check if a DE app exists first, and return an `ERR_NOT_FOUND` before checking the user's app permissions.
This PR also removes some obsolete code.

CORE-7507 Update the apps is-publishable endpoint to check for app existence first

---

src/apps/clients/permissions.clj
src/apps/metadata/element_listings.clj
src/apps/routes/schemas/containers.clj
src/apps/routes/schemas/tool.clj
src/apps/routes/tools.clj
src/apps/tools.clj
src/apps/tools/permissions.clj
src/apps/tools/private.clj
src/apps/util/config.clj

Private tools are currently not allowed to mount any devices or volumes, and have restrictions on networking (none), resources (4 CPUs / 8GB RAM), and run duration (24 hours). If implementation details are not provided in the request, then the requesting user's name and email will be used by default.
This PR also adds permission checks on tool listings and private tool details.
Admin endpoints will not currently list a private tool if the admin does not have permissions on that tool.

CORE-8691 Add a `POST /tools` endpoint that allows users to add private tools

---

src/apps/clients/notifications.clj
src/apps/clients/notifications/tool_sharing.clj
src/apps/clients/permissions.clj
src/apps/routes/schemas/permission.clj
src/apps/routes/tools.clj
src/apps/service/apps/de/sharing.clj
src/apps/tools/permissions.clj
src/apps/tools/sharing.clj

This PR adds `POST /tools/sharing` and `POST /tools/unsharing` endpoints.
These endpoints will send tool (un)sharing notifications to the sharer and sharee as appropriate.
Also, when a user shares an app that uses private tools, those tools are also shared with `read` access.

CORE-8692: Add endpoints that allow users to (un)share private tools

---

src/apps/clients/permissions.clj
src/apps/containers.clj
src/apps/metadata/element_listings.clj
src/apps/persistence/app_metadata.clj
src/apps/persistence/tools.clj
src/apps/routes/schemas/permission.clj
src/apps/routes/tools.clj
src/apps/service/apps/de/listings.clj
src/apps/service/integration_data.clj
src/apps/tools.clj
src/apps/tools/permissions.clj
src/apps/tools/private.clj
src/apps/tools/sharing.clj

This PR adds a `POST /tools/permission-lister` endpoint.
To prevent a circular dependency between `apps.tools.permissions` and `apps.tools`, the 2nd commit of this PR refactors tools db functions out of `apps.tools` and `apps.persistence.app-metadata` into `apps.persistence.tools`.
The last commit actually adds the new endpoint.

CORE-8722 Add POST /tools/permission-lister

---

src/apps/containers.clj
src/apps/routes/schemas/tool.clj
src/apps/routes/tools.clj
src/apps/tools/private.clj
src/apps/validation.clj
test/apps/service/apps/public_apps_test.clj

This PR adds a `PATCH /tool/:tool-id` endpoint to allow users to update their private tools.
As with the `POST /tools` endpoint, `type` is always set to `executable` and `restricted` is always set to `true`, even if other values are set in the request, and a configured limit may override the `time_limit_seconds` field set in the request.
Also, similar to the `PATCH /admin/tool/:tool-id` endpoint, if the `container` object is omitted in the request, then existing container settings will not be modified, but if the `container` object is present in the request, then all container settings must be included in it. Any existing settings not included in the request's `container` object will be removed, except `network_mode` is always set to `none` and configured limits may override values set …

CORE-8693 Add `PATCH /tool/:tool-id` endpoint.

---

project.clj
src/apps/persistence/app_metadata.clj
src/apps/persistence/tools.clj
src/apps/routes/schemas/tool.clj
src/apps/routes/tools.clj
src/apps/tools.clj
src/apps/tools/private.clj

This PR adds a `DELETE /tools/:tool-id` endpoint that allows a user to delete a private tool, as long as it is not in use by any apps.
The requesting user must have ownership permission for the tool.
If the tool is already in use in private apps, then an `ERR_NOT_WRITEABLE` will be returned along with a listing of the apps using this tool (same as the `DELETE /admin/tools/:tool-id` endpoint); unless the `force-delete` flag is set to `true`, then the tool will be removed from those apps and then deleted.

CORE-8694 Add DELETE /tools/:tool-id endpoint.

---

src/apps/persistence/tools.clj
src/apps/routes/params.clj
src/apps/routes/schemas/tool.clj
src/apps/routes/tools.clj
src/apps/tools.clj

This PR updates the `GET /tools` listing endpoint (which also updates the `GET /apps/elements/tools` listing response):
* The `search` param is now optional.
* An optional `public` param now allows `GET /tools` to return only public, only private, or all tools.
* The tool's Docker image `name` and `tag` are now included in listing results.
* The tool's implementor name and implementor email are now included in listing results.
* The `search` param can now match a tool's Docker image name, integrator name, or integrator email.

CORE-8748 / CORE-7531: Update tool listings and search

---

src/apps/persistence/tools.clj
src/apps/routes/schemas/tool.clj
src/apps/routes/tools.clj
src/apps/tools.clj
test/apps/service/apps/test_fixtures.clj
test/apps/tools_test.clj

This PR adds admin endpoints to list all tools and fetch details for any tool.
The swagger docs for some /admin/tools endpoints were also updated, and the `PATCH /admin/tools/:id` endpoint now validates a tool exists before attempting to update it.

CORE-8697 Add `GET /admin/tools` and `GET /admin/tools/:tool-id` endpoints

---

src/apps/routes/schemas/tool.clj
src/apps/tools.clj
src/apps/tools/private.clj
src/apps/validation.clj
test/apps/service/apps/test_fixtures.clj

This PR allows the `location` field to be optional in `tools` endpoints, since all new tools are using Docker images and the `location` field is no longer required for running new tools.
Since we have many tools with duplicate names, this PR also makes the `version` field required (also updated by cyverse-de/de-db#8).

CORE-8745 Make tool version required and location optional.

---

src/apps/metadata/tool_requests.clj
src/apps/routes/schemas/tool.clj

The `POST /tool-requests` endpoint no longer requires the `architecture` field.
Since a `tool_architecture_id` is still required by the `tool_requests` db table, the service will default this value to `Others` if it's not sent in the request from the client.

CORE-8746 Allow tool request `architecture` field to be optional.

---

src/apps/routes/schemas/app.clj
src/apps/service/apps/de/edit.clj

Allows the UI to pass extra tool listing fields in the request body of the apps add, edit, and arg-preview endpoints, since it's not filtering those tool fields it gets from the listing endpoint when submitting the tools with an app request.
The the response of the `PUT /apps/{system-id}/{app-id}` endpoint also needed to be updated to the same response as the `GET /apps/{system-id}/{app-id}/ui` endpoint in order to avoid returning these extra tool fields received from the UI.

CORE-8811 Update Tool schema in apps add/edit and arg-preview endpoints.

---

src/apps/containers.clj
src/apps/routes/schemas/containers.clj
src/apps/routes/tools.clj

The corresponding columns have already been added to the container_settings table in the DE database.
I tried out the new endpoints through swagger against a local database. The patch endpoint for tools hasn't been tested yet because of the additional service dependencies.

Resource limits

---

src/apps/metadata/tool_requests.clj
src/apps/persistence/tool_requests.clj
src/apps/routes/schemas/tool.clj

A `tool_id` may now be submitted in new tool requests, and it will be returned in tool request details.
The following endpoints have been updated with a `tool_id` field:
* `GET /admin/tool-requests/{request-id}`
* `POST /admin/tool-requests/{request-id}/status`
* `POST /tool-requests`

CORE-8749 Add `tool_id` to tool-requests endpoints.

---

src/apps/containers.clj
src/apps/metadata/element_listings.clj
src/apps/metadata/tool_requests.clj
src/apps/persistence/app_metadata.clj
src/apps/persistence/tools.clj
src/apps/routes/schemas/app.clj
src/apps/routes/schemas/containers.clj
src/apps/routes/schemas/tool.clj
src/apps/routes/tools.clj
src/apps/service/apps/de/edit.clj
src/apps/service/apps/de/validation.clj
src/apps/tools.clj
src/apps/tools/private.clj
src/apps/validation.clj
test/apps/containers_test.clj

This PR adds the `deprecated` flag to tool details in app and tool listing endpoints.
The following endpoints now use the `deprecated` flag in the tool JSON object:
* `PUT /apps/{system-id}/{app-id}`
* `POST /apps/{system-id}/{app-id}/copy`
* `GET /apps/{system-id}/{app-id}/ui`
The following endpoints now use the `deprecated` flag in the tool's container image JSON object:
* `GET /admin/apps/{system-id}/{app-id}/details`
* `GET /admin/tools`
* `POST /admin/tools`
* `GET /admin/tools/container-images`
* `POST /admin/tools/container-images`
* `GET /admin/tools/container-images/{image-id}`
* `PATCH /admin/tools/container-images/{image-id}`
* `GET /admin/tools/{tool-id}`
* `PATCH /admin/tools/{tool-id}`
* `GET /apps/{system-id}/{app-id}/details`
* `GET /tools`
* `POST /tools`
* `GET …

CORE-8750: Add `deprecated` flag to tool images

---

src/apps/routes/schemas/app.clj
src/apps/service/apps/de/listings.clj
src/apps/service/apps/de/pipeline_edit.clj

This PR will add tool details to each DE task in the following endpoint responses:
* `GET /apps/de/{app-id}/tasks`
* `GET /apps/pipelines/{app-id}/ui`
This will allow the UI to check for deprecated tools in apps added to workflows, or already included in workflows when first opened for editing.

CORE-8857 Add tool details to app tasks and pipeline ui endpoints.

---

src/apps/clients/permissions.clj
src/apps/routes/tools.clj
src/apps/tools.clj

Adds an endpoint for admins to make tools public, also allowing the admin to make updates to the tool in the same request.

CORE-8695 Add POST /admin/tools/{tool-id}/publish

---

src/apps/persistence/tools.clj
src/apps/routes/schemas/tool.clj
src/apps/tools.clj

This PR adds tool request info like the following to tool listings, if the tool has a tool request associated with it:
```json
{
"tool_request": {
"id": "uuid",
"status": "string"
}
}
```
The following endpoints have been updated with this response info:
* `GET /admin/tools`
* `GET /apps/elements/tools`
* `GET /tools`

CORE-8747 Add tool request ID and status to tool listings.

---

src/apps/metadata/tool_requests.clj
src/apps/persistence/tool_requests.clj
src/apps/routes/schemas/tool.clj

This change probably should have been part of cyverse-de/apps#58 (CORE-8749).
Also includes a fix for `ToolRequestSummary` docs, inadvertently affected by changes for CORE-8747.

CORE-8877 Add `tool_id` to (/admin)/tool-requests endpoint responses.

---

src/apps/metadata/tool_requests.clj
src/apps/persistence/tool_requests.clj
src/apps/routes/tools.clj
src/apps/tools.clj

This PR updates the `POST /admin/tools/{tool-id}/publish` endpoint to auto-complete the tool request for the given tool.
This also required that I move new tool request `tool-id` validation into `apps.tools` to avoid a circular dependency with `apps.metadata.tool-requests`.
I also added a check for an existing tool request for the given `tool-id`, otherwise tool listings for tools with 2 tool requests would be duplicated, since tool listings now include the latest tool request status.

CORE-8882 Update admin tool publish endpoint to complete tool requests.

---

src/apps/routes/schemas/containers.clj
src/apps/routes/tools.clj
src/apps/tools/private.clj
src/apps/util/config.clj

This PR removes the `cpu_shares` limit automatically added to private tools, replacing it with initial support for `pids_limit` restrictions in the `POST /tools` endpoint.
The `pids_limit` is only added in this PR as a config setting (64 by default) and as an allowed `container` field in tool requests, but since it's not persisted in the database yet, it won't be returned in tool info or submitted with job info.

CORE-8885 Replace private tools cpu_shares limit with pids_limit.

---

src/apps/containers.clj

The `POST (/admin)/tools` and `PATCH (/admin)/tools/:id` endpoints will now save `pids_limit` container settings to the db. This setting will also now be included in `GET (/admin)/tool/:id` responses and in job submissions.
Note that this PR depends on cyverse-de/de-db#13 getting merged first.

CORE-8885 Update (/admin)/tools endpoints to persist pids_limit setting.

---

src/apps/containers.clj
src/apps/persistence/app_metadata.clj
src/apps/validation.clj

Updated the `DELETE` and `PATCH /admin/tools/container-images/:id` endpoint validations to look for all tools using the given image, not just for tools already used in apps, and also to check for tools using the given image as a data container.
Also renamed some functions related to images in public apps for clarity, since tools can be private now.

CORE-7290 Fix DELETE/PATCH /admin/tools/container-images/:id validation.

---

src/apps/routes/schemas/tool.clj
src/apps/routes/tools.clj

Added a `GET /admin/tools/container-images/{image-id}/public-tools` listing response schema with fewer details than the schema used by `GET (/admin)/tools`, since this endpoint does not use the tool listing and formatting functions that include the extra details required for the `(/admin)/tools` listing endpoints.
This fixes response schema validation errors for images used by public apps.

CORE-8921 Add ImagePublicAppToolListing response schema.

---

src/apps/clients/data_info.clj
src/apps/service/apps/jobs/submissions.clj

As far as I can tell these are the things which are needed in each of these calling locations. `lein check` and `lein eastwood` and `lein kibit` are fine with this code. I've dealt with every location that previously called `apps.clients.data-info/get-file-stats`, since I changed the name.

Allow using the path-info endpoint, add filtering.

---

apps.properties.tmpl
src/apps/clients/notifications.clj
src/apps/persistence/jobs.clj
src/apps/service/apps/agave/jobs.clj
src/apps/service/apps/de/jobs.clj
src/apps/service/apps/jobs.clj
src/apps/service/apps/jobs/submissions.clj
src/apps/service/apps/jobs/submissions/async.clj
src/apps/service/apps/jobs/submissions/submit.clj
src/apps/util/config.clj

This PR will migrate batch job submissions into a separate thread, allowing the `POST /analyses` endpoint to submit the parent job and respond to the client right away, while sub-jobs are submitted in the background thread.
Once the background thread submits all sub-jobs, it will send a notification to the user which includes the count of successful sub-job submissions. If an exception is caught, or if all sub-jobs fail to submit, then the parent job will be marked as failed, and the user will receive a job failure notification for the parent.
This will allow us to lift the 128-paths limit on jobs submitted with HT Path List files to something much larger. We should probably keep some limit in place for now, until we have async job submissions that are 0-downtime compatible, since these …

CORE-9016 Make HT Path List job submissions async

---

src/apps/persistence/jobs.clj
src/apps/service/apps/jobs.clj

This PR will update `apps.service.apps.jobs/stop-job` to also stop all child jobs, even if the parent job has already been stopped in a previous request.
Stopping child jobs will run async in a named thread, allowing the endpoint to respond to the client right away.

CORE-9014 Update analyses stop endpoint to also stop all child jobs.

---

apps.properties.tmpl
src/apps/persistence/jobs.clj
src/apps/service/apps/agave/jobs.clj
src/apps/service/apps/combined/jobs.clj
src/apps/service/apps/de/jobs.clj
src/apps/service/apps/jobs/submissions.clj
src/apps/service/apps/jobs/submissions/async.clj
src/apps/service/apps/jobs/util.clj
src/apps/util/config.clj

This PR will add job submission support for a new `multi-input-path-list` file info-type, which is only valid for use in Multi-Input app parameters.
This info-type is defined in cyverse-de/heuristomancer#4.
The current strategy for `Multi-Input Path List` job submission support is to have this service "expand" the path-list contents in the input parameter job submission JSON, by replacing the original path with the downloaded list of paths.
This is similar to the strategy used for HT Path List files, except the "Multi-Input Path List expansion" does not need to be asynchronous, since the replacement can be done in a reasonable amount of time.
A bigger consideration is that a path list file of 100k paths can have a file size around 100MB, which means the JSON submission to the job services …

CORE-9057 Add Multi-Input Path List job submission support

---

src/apps/persistence/app_groups.clj
src/apps/persistence/jobs.clj
src/apps/persistence/util.clj

This PR will add an `apps.persistence.util/sqlfn-any-array` for use in a `where` clause, in order to prevent a `PSQLException` when passing too many items in a `(when {:id [in id-list]})` clause.
The `PSQLException` (caused by `java.io.IOException`: "Tried to send an out-of-range integer as a 2-byte value") is thrown because the JDBC driver is hitting a limit on the number of bind variables per PostgreSQL statement.

CORE-9082 Prevent PSQLException in the GET /analyses endpoint when user has 32k+ jobs/sub-jobs

---

src/apps/persistence/jobs.clj
src/apps/service/apps/job_listings.clj

This PR will update the `GET /analyses` listing endpoint to use SQL queries to count the statuses for child jobs for batch job listings.
This will speed up the `GET /analyses` endpoint when listing large batch jobs.

CORE-9084 Speed up `GET /analyses` listing endpoint.

---

src/apps/service/apps/jobs/submissions/async.clj

This PR will fix the `POST /analyses` endpoint for HT Path List file inputs.
A bug was introduced to batch job processing by #86, which required a new `job_config` submission setting for Multi-Input Path List inputs.
Since #86, the user's original submission `config` is stored in the database for re-launching jobs, but the new `job_config` submission setting is used to submit actual parameters to the job services. The `job_config` submission setting is just a copy of the original submission `config` for jobs without any Multi-Input Path List inputs.
This PR will fix the `apps.service.apps.jobs.submissions.async/format-submission-in-batch` function so that it also substitutes HT path inputs in each sub-job's `job_config` submission settings.

CORE-9086 Fix `job_config` in `format-submission-in-batch` function.

---

src/apps/routes/schemas/permission.clj
src/apps/service/apps/jobs/sharing.clj

The `/analyses/sharing` and `/analyses/unsharing` endpoints have been updated to return error messages for any input (un)share errors, but job (un)shares can still be marked as a `success` with those errors.
Most (un)sharing validation functions have been refactored to throw exceptions for errors, which are caught in the calling (un)sharing function and formatted as a failure message. Also, these endpoints used to return only the first input (un)sharing failure message, but this PR collects all failure messages and returns them in the response.

CORE-7576 Update (un)share analyses to allow input (un)share errors.

---

src/apps/clients/data_info.clj
src/apps/service/apps/de/jobs/io_tickets.clj
src/apps/service/apps/jobs/submissions.clj
src/apps/service/apps/jobs/util.clj

This PR will add `apps.service.apps.de.jobs.io-tickets/update-with-download-tickets` for use with
`apps.service.apps.de.jobs.protocol/buildInputs` and `update-with-output-dir-ticket` for use with `buildSubmission`.
These new functions will use a new `apps.clients.data-info/create-tickets` function for calling the `data-info` endpoint.
Also refactored `apps.service.apps.jobs.submissions/get-batch-output-dir` into a common `apps.service.apps.jobs.util/create-output-dir` function, for use in both `update-with-output-dir-ticket` and batch output folder creation.

CORE-9189 Update to create tickets for inputs and output folders for use in OSG submissions

---

src/apps/service/apps/de/jobs/common.clj

Previously, the execution_target field in job submissions was hardcoded to "condor". This pull request changes it so that it will be set to "interapps" if any of the steps has the component.container.interactive field set to true. This should be fairly easy to extend to other execution targets in the future.

Enable the "interapps" execution target

---

src/apps/containers.clj
src/apps/routes/schemas/containers.clj

Adds support for the container_settings.skip_tmp_mount column to the apps API and to job submissions.
I tried out the changes through the Swagger UI.

Add support for skip_tmp_mount column

---

project.clj
src/apps/clients/notifications.clj
src/apps/util/config.clj

Sarah will be adding support for an interactive apps analysis type later on, at which point we'll be able to add the URL for the interactive app to the Running job status notifications as appropriate. This pull request adds the (interapps-url) function and the (configs/interapps-base) setting to the apps service, so that the URLs can be generated correctly.

Add (interapps-url) function for later use in notifications

---

src/apps/containers.clj
src/apps/routes/schemas/containers.clj

min_cpu_cores for container settings was changed to a Double.
max_cpu_cores for container settings was added as a Double.

Modify min_cpu_cores, add max_cpu_cores for container settings.

---

src/apps/containers.clj
src/apps/routes/schemas/containers.clj

This should allow the `uid` field to be set on the container_settings table through the apps service.

Add the uid field to container-settings

---

src/apps/clients/notifications.clj
src/apps/persistence/app_metadata.clj

This may not be the last PR associated with this change. Some notification format changes might be necessary in cases where the notification type is `data`. I want to get this change deployed in our development environment for testing, though.

CORE-6903: change the notification type for URL upload jobs

---

src/apps/persistence/jobs.clj
src/apps/routes/analyses.clj
src/apps/routes/schemas/analysis.clj
src/apps/service/apps.clj
src/apps/service/apps/jobs.clj

I still need to test this more than I have, but I wanted to get it up for review. I've also made it so when we stop jobs we put an entry in the `job_status_updates` table, though we do so after setting the real status. I haven't yet evaluated if I should force a propagation of job status updates at the same time, to reduce load elsewhere.

CORE-9306: allow setting a specific status code when stopping jobs

---

src/apps/protocols.clj
src/apps/routes.clj
src/apps/routes/admin.clj
src/apps/routes/apps/categories.clj
src/apps/routes/schemas/app/category.clj
src/apps/service/apps.clj
src/apps/service/apps/agave.clj
src/apps/service/apps/combined.clj
src/apps/service/apps/de.clj
src/apps/service/apps/de/listings.clj
src/apps/util/config.clj

This PR will add `(/admin)/apps/communities/{community-id}/apps` endpoints for listing apps tagged with a community AVU for #125.
Currently checks an Agave app's ontology list for the community group's name, though this may not be appropriate for this kind of tag.

Add /apps/communities/{community-id}/apps endpoints.

---

src/apps/routes/schemas/containers.clj
src/apps/routes/schemas/tool.clj
src/apps/routes/tools.clj
src/apps/util/coercions.clj

This PR will add container settings String->Long coercion middleware, which allows container settings that require Long integer values to be submitted as either a JSON number or a string representation.
This resolves #136.

Add container settings String->Long coercion middleware.

---

src/apps/service/apps/de/jobs/common.clj
src/apps/service/apps/de/jobs/condor.clj
src/apps/service/apps/de/jobs/protocol.clj

This pulls the `extra_requirements` column from `apps_htcondor_extra` and adds it to the submission.
Still needs the downstream jex-adapter etc. work, of course, but hopefully if I did anything too blatantly dumb it can get caught here :laughing:

CORE-63: Add code to load extra fields when submitting

---

project.clj
src/apps/routes/admin.clj
src/apps/routes/apps.clj
src/apps/routes/schemas/app.clj
src/apps/routes/schemas/permission.clj

Migrated `/apps/shredder`, `permission-lister`, `sharing`, and `unsharing` docs into the `common-swagger-api` lib.

CORE-11 Migrate some /apps endpoint schemas.

---

src/apps/routes/admin.clj
src/apps/routes/apps/categories.clj
src/apps/routes/schemas/app.clj
src/apps/routes/schemas/app/category.clj

This PR will replace some of the schemas in `apps.routes.schemas.app` and `apps.routes.schemas.app.category`, and some `apps.routes.apps.categories` docs, with those migrated to `common-swagger-api.schema.apps.categories` in cyverse-de/common-swagger-api#17

CORE-11 Migrate /apps/categories schemas and docs

---

project.clj
src/apps/routes/admin.clj
src/apps/routes/apps/categories.clj
src/apps/routes/schemas/app/category.clj

This PR will use the `/apps/hierarchies` endpoint docs and schemas migrated in cyverse-de/common-swagger-api#18.

CORE-11 Migrate /apps/hierarchies docs and schemas

---

src/apps/routes/admin.clj
src/apps/routes/apps/categories.clj
src/apps/routes/schemas/app/category.clj

This PR will use the community app listing docs migrated by cyverse-de/common-swagger-api#20.

CORE-11 Migrate GET /apps/communities/{community-id}/apps docs

---

project.clj
src/apps/clients/metadata.clj
src/apps/metadata/avus.clj
src/apps/routes/apps/communities.clj
src/apps/routes/apps/metadata.clj
src/apps/service/apps/de/categorization.clj

This PR will update `/apps/{app-id}/metadata` endpoint docs to use the AVU schemas and docs added by cyverse-de/common-swagger-api#21.
This also requires the updated metadata-client functions added by cyverse-de/metadata-client#5.

CORE-11 Use common-swagger-api metadata docs and schemas

---

src/apps/routes/apps/communities.clj

This PR will replace `/apps/{app-id}/communities` endpoint docs and schemas in `apps.routes.apps.communities` with those added by cyverse-de/common-swagger-api#22.

CORE-11 Migrate /apps/{app-id}/communities docs

---

project.clj
src/apps/routes/apps/elements.clj
src/apps/routes/params.clj
src/apps/routes/schemas/containers.clj
src/apps/routes/schemas/permission.clj
src/apps/routes/schemas/tool.clj
src/apps/routes/tools.clj

This PR will replace the remaining `/tools` endpoint schemas and docs in `apps.routes.tools` with those added by cyverse-de/common-swagger-api#23.

CORE-11 Migrate remaining /tools endpoint schemas and docs

---

project.clj
src/apps/routes/params.clj

This PR will update apps with `common-swagger-api` version `2.11.3`, which includes a bug fix for listing batch job status counts.
It will also update `apps.routes.params/AnalysisListingParams` to merge `SecuredQueryParams` with `common-swagger-api.schema.analyses.listing/AnalysisListingParams`, which now includes paging params in the latest `common-swagger-api` version.

CORE-11 Bump common-swagger-api to release version 2.11.3

---

project.clj
src/apps/routes/schemas/containers.clj
src/apps/routes/schemas/tool.clj
src/apps/routes/tools.clj
src/apps/util/coercions.clj

This PR will replace `apps.routes.schemas.tool/coerce-tool-import-requests` and `coerce-tool-list-import-request` (and related functions) with those added by cyverse-de/common-swagger-api#28.
Missed in #165.

CORE-11 Migrate coerce-tool-import-requests middleware

---

project.clj
src/apps/routes/admin.clj
src/apps/routes/schemas/tool.clj
src/apps/routes/tools.clj

This PR will replace the schemas and docs in `apps.routes.tool` and `apps.routes.schemas.tool` with those added by cyverse-de/common-swagger-api#31.

CORE-11 Migrate remaining /tool-requests endpoint schemas and docs

---

project.clj
src/apps/routes/admin.clj
src/apps/routes/reference_genomes.clj
src/apps/routes/schemas/reference_genome.clj

This PR will replace the schemas and docs for `/reference-genomes` endpoints with those added by cyverse-de/common-swagger-api#32.

CORE-11 Migrate schemas and docs for /reference-genomes endpoints

---

project.clj
src/apps/routes.clj
src/apps/routes/admin.clj
src/apps/routes/admin/apps.clj
src/apps/routes/analyses.clj
src/apps/routes/integration_data.clj
src/apps/routes/params.clj
src/apps/routes/schemas/app.clj
src/apps/routes/schemas/app/category.clj
src/apps/routes/tools.clj
src/apps/service/util.clj

This PR will replace the schemas and docs for `/admin/apps` endpoints with those added by cyverse-de/common-swagger-api#33.
It will also refactor the `/admin/apps` endpoints into a new `apps.routes.admin.apps` namespace.

CORE-11 Migrate schemas and docs for /admin/apps endpoints.

---

project.clj
src/apps/persistence/app_listing.clj
src/apps/persistence/app_metadata.clj
src/apps/persistence/entities.clj
src/apps/service/apps/de/admin.clj
src/apps/service/apps/de/listings.clj

This allows the field to be added in the administrative app PATCH endpoint, and returns it in the administrative app details endpoint.
Depends on cyverse-de/common-swagger-api#36 and cyverse-de/common-swagger-api#37 but the relevant snapshot version was already what was in project.clj of this project, so the changes are only to the functionality of the endpoints themselves.
It may also be useful to add documentation information into the app details endpoint, as we discussed at one point. That hasn't happened yet, but could get added to this PR or go into a new one.
We'll also need to pull the new common-swagger-api version into terrain, but I don't see much need to make a PR for just that :)

CORE-63: Add handling for htcondor extra requirements

---

src/apps/routes/schemas/tool.clj
src/apps/routes/tools.clj

This PR will replace schemas and docs for `/admin/tools` endpoints with those added by cyverse-de/common-swagger-api#39.

CORE-11 Migrate schemas and docs for /admin/tools endpoints

---

src/apps/routes.clj
src/apps/routes/admin.clj
src/apps/routes/admin/tool_requests.clj
src/apps/routes/schemas/tool.clj

This PR will replace the `/admin/tool-requests` endpoint schemas and docs with those added by cyverse-de/common-swagger-api#40, and refactor `/admin/tool-requests` endpoints into their own `apps.routes.admin.tool-requests` namespace.

CORE-11 Migrate schemas and docs for /admin/tool-requests endpoints

---

src/apps/clients/notifications.clj
src/apps/service/apps/de/metadata.clj

The app publish endpoint will no longer auto-tag apps with communities.
Instead, community admins will now receive notifications that the integrator wishes to tag their public app with those communities.
All other metadata, including ontology tags, are still added to the app.

CORE-324 Update app publish endpoint to only notify community admins.

---

project.clj
src/apps/tools.clj

I realized this piece was missing for the tool listing endpoint to be ready for pagination.

CORE-463 Add total count to tool listing endpoint

---

project.clj
src/apps/routes/analyses.clj

This PR will update the `POST /analyses` endpoint with the `coerce-analysis-submission-requirements` middleware added by cyverse-de/common-swagger-api#51.

CORE-468 Add coerce-analysis-submission-requirements middleware.

---

project.clj
src/apps/service/apps/jobs/params.clj

This PR will update the `GET /analyses/{analysis-id}/relaunch-info` endpoint to include `default_memory`, `default_cpu_cores`, and `default_disk_space` values in each step's resource `requirements` settings, if the corresponding `min` values were submitted in the original analysis.
Merging requires cyverse-de/common-swagger-api#53 first.

CORE-633 Add submitted resources reqs as defaults in relaunch response

---

project.clj
src/apps/routes/analyses.clj
src/apps/service/apps.clj
src/apps/service/apps/jobs.clj
src/apps/service/apps/jobs/resubmit.clj
src/apps/service/apps/jobs/submissions.clj
src/apps/service/apps/jobs/submissions/async.clj

This PR will add the new `POST /analyses/relauncher` endpoint.
From the endpoint docs added in cyverse-de/common-swagger-api#54:
This service automatically relaunches analyses with the IDs given in the request.
* If a requested analysis was a sub-job of an HT analysis, then the relaunched analysis will also be a sub-job of that parent HT analysis.
* Any of the original analyses that have the `create_output_subdir` flag set to `false` will cause the corresponding relaunched analysis to use an output folder with `-redo-###` appended to the original output folder name, where `###` will be a `1` by default. If the original output folder name also ends with `-redo-###`, then the relaunched folder name will use a number 1 larger than the original. This will always apply to output folders of …

CORE-661 Add `POST /analyses/relauncher` endpoint

---

project.clj
src/apps/persistence/app_listing.clj
src/apps/protocols.clj
src/apps/routes/apps.clj
src/apps/service/apps.clj
src/apps/service/apps/agave.clj
src/apps/service/apps/agave/listings.clj
src/apps/service/apps/combined.clj
src/apps/service/apps/de.clj
src/apps/service/apps/de/listings.clj

The changes in this PR add a new endpoint that can be used to obtain app listing information for a single app.
The purpose of adding a separate endpoint for listing a single app in the DE is also to add clarity. Adapting the existing app search endpoint to work for listing a specified app ID seems potentially confusing. For example, what happens if the app-id and search parameters are both specified and they conflict (that is the app ID matches an app, but the search string would exclude the app)? I can imagine a valid argument for excluding the app because it doesn't match the search string. After all, maybe the caller only wants to list that specific app if it also matches the search string. I can also imagine a valid argument for including the app because the app-id parameter should …

CORE-971: added an endpoint to list a single app in the DE

---

src/apps/service/apps.clj
src/apps/service/apps/de/listings.clj

also, remove non-public categories faster with futures and doall
fairly small PR, but improves performance of the main categories endpoint substantially. apps was doing some significant work it didn't need to, plus this parallelizes some of what's left. Here's what's going on:
`count-deleted-and-orphaned-apps` is pretty slow (about 5s from here, though it's probably at least a little better not over VPN). But, it's only used for the Trash category, which has `:is_public` set to true. `format-private-virtual-groups` removes things with `:is_public` true, but only after they've been calculated out, so we were just calculating that all out to immediately toss it. Instead, I've changed it to use a future for all the counts, and then deref the futures after the `remove` call. Also, I added in …

Parallelize creation of virtual categories

---

project.clj
src/apps/persistence/jobs.clj
src/apps/protocols.clj
src/apps/routes/analyses.clj
src/apps/routes/params.clj
src/apps/service/apps.clj
src/apps/service/apps/agave.clj
src/apps/service/apps/combined.clj
src/apps/service/apps/de.clj
src/apps/service/apps/job_listings.clj

In case we did want to switch to having the totals be grouped by job type (so, for example, an interactive section with all those status totals, and then an agave section with all those status totals, etc.), instead of showing the totals for whatever type filter is set, I've been looking into how to do that as well (if only for my own practice). It's taking me longer than I anticipated to figure that out, so I'm putting this up now in case we want to stick with this format anyway. So the end result is still looking like:
```
{
"analyses": [ ... ],
"timestamp": "1591988105298",
"status-count": [
{
"count": 23,
"status": "Submitted"
},
{
"count": 3,
"status": "Canceled"
},
{
"count": 4,
"status": "Completed"
}
],
"total": 30
}
```

CORE-600 Add job status counts as an endpoint and to job listings

---

conf/test/logback.xml
src/apps/service/apps/combined.clj
src/apps/service/apps/combined/util.clj

I tested these changes locally in the REPL using these functions:
``` clojure
(defn test-search
[term]
(binding [current-user user]
(apps/search-apps user {:search term})
nil))
(defn test-admin-search
[term]
(binding [current-user user]
(apps/admin-search-apps user {:search term})
nil))
(def ontology-version "http://edamontology.org/1.16/2016/12/19/15-54-46.2")
(def root-iri "http://edamontology.org/operation_2928")
(def attr "rdf:type")
(def sort-field "name")
(def sort-dir "ASC")
(defn test-list-apps-under-hierarchy
[]
(binding [current-user user]
(apps/list-apps-under-hierarchy
user
root-iri
attr
{:type       attr
:sort-field sort-field
:sort-dir   sort-dir})
nil))
(defn test-admin-list-apps-under-hierarchy
[]
(binding [current-user user]
(apps/admin-list-apps-under-hierarchy
user …
```

CORE-1102: perform DE an HPC analysis listings concurrently.

---

src/apps/persistence/app_listing.clj
src/apps/service/apps/combined.clj
src/apps/service/apps/de/listings.clj

After doing some more testing, I think that this PR and the previous one combined make all of the changes that will be useful to make at this time. We could migrate other endpoints to the new listing queries, but that's going to require more effort than it's worth at the moment.
This PR updates the endpoints to list apps under an ontology hierarchy, and it removes the `:new` parameter that I had been using to switch between the old and new queries.

CORE-1106: more app listing improvements

---

src/apps/persistence/jobs.clj
src/apps/service/apps/job_listings.clj

This change reduced the number of queries that are made during analysis listing in order to improve the responsiveness of the listing endpoints.

CORE-1110 analysis listing performance improvements.

---

project.clj

This is just a dependency update. I'm going to merge it immediately.

CORE-1217: switched to a newer version of org.cyverse/mescal

---

project.clj

Updated from 3.0.4 to 3.0.6.
it was 3.0.5 in [project.clj](https://github.com/cyverse-de/kameleon/compare/10d0dc6cfc7a...0e740123fa39). Does that mean it wasn't updated before?

Update kameleon version

---

project.clj
src/apps/clients/data_info.clj
src/apps/clients/permissions.clj
src/apps/persistence/jobs.clj
src/apps/service/apps/job_listings.clj

This PR improves the performance of two components of analysis listing:
- listing permissions for all analyses that a user may access.
- listing representative job steps for the analyses in the listing
For the time being, the permissions listing improvement is achieved by eliminating some of the unnecessary data from the permission listing. In one case where the timeout was occurring, the user had access to more than 15000 analyses. Serializing and deserializing that many permissions was taking a significant amount of time, so a new endpoint was created for an abbreviated permission listing that omits some of the data that wasn't being used in this case. This change shortened the response time by a little more than a second in most cases.
After the database merge is complete, we're …

CORE-1416: improve analysis listing performance

---

src/apps/clients/permissions.clj

For CORE-1416, the abbreviated permissions by subject and resource type endpoint was added for performance improvements.  This resulted in the response body from the permissions service changing to a shorter, flatter JSON object.  The resource name is no longer nested in `resource.name`, it's in `resource_name`.  The `resource-id-filter` function just needed to be updated to match this new model.
I tested deleting multiple analyses and that's now working.  The CORE-1416 change was mostly for speeding up the analysis listing performance so I checked that as well and it seems to still work.

CORE-1461 Users unable to delete multiple analyses

---

src/apps/containers.clj
src/apps/persistence/docker_registries.clj

Instead of taking everything up to the last slash, split on slashes, then repeatedly check for registry information starting with the full name, then removing slash-separated parts starting from the end. This way, it should work for any slash-separated prefix match.
Would appreciate some extra eyes on this since I'm feeling like I missed something in the logic, but anyway.

CORE-1489: be smarter about fetching docker registry authentication information

---

project.clj

Updates the version of common-swagger-api. This should enable analysis submissions to include the max_cpu_cores field. That doesn't mean the service does anything with the field yet, that's still being looked at.

Update common-swagger-api to 3.2.3

---

src/apps/service/apps/de/jobs/common.clj

The `max_cpu_cores` request submitted from the client was ignored and not used in submissions to the job services.
This PR will update the job submission endpoint use the `max_cpu_cores` request submitted from the client, as long as it's less than the tool's default restriction.
Will also use max `memory_limit` from the client in the same way, if the endpoint is updated in the future to allow it in requests.

CORE-1741 Use client max CPU if lower than tool default

---

project.clj
src/apps/service/apps/jobs/params.clj

This PR will add a `default_max_cpu_cores` field to `relaunch-info` endpoint responses, populated from the user's original `max_cpu_cores` request.

CORE-1745 Add default_max_cpu_cores to relaunch-info responses

---

src/apps/persistence/app_metadata.clj

This PR will update the `PUT /admin/apps/:system-id/:app-id/integration-data/:integration-data-id` endpoint so that it will update an app's latest version.
This should have been part of the changes for #246.

CORE-1749 Fix admin integration-data update endpoint for app versions

---

src/apps/persistence/app_metadata.clj

This PR will fix the `DELETE /admin/integration-data/:integration-data-id` endpoint so that it will check the `app_versions` table for integration data in use by apps.
This should have been part of the changes for #246.

CORE-1750 Fix admin integration-data delete endpoint for app versions

---

project.clj
src/apps/persistence/app_metadata.clj
src/apps/routes/admin/apps.clj
src/apps/service/apps.clj
src/apps/service/apps/de/admin.clj
src/apps/service/apps/de/edit.clj
src/apps/service/apps/de/listings.clj
src/apps/service/apps/de/metadata.clj
src/apps/service/apps/de/pipeline_edit.clj
src/apps/service/apps/de/validation.clj

This PR will add admin app version details and update endpoints.
It will also update the sharing endpoint to only share tools in undeleted versions, and the publish endpoints to only validate and publish tools in undeleted versions.
This change now requires admin undelete actions for app versions to ensure tools are not private or missing, and also ensures workflows are using tasks from public apps; and these validation checks are also now in the create version endpoints for public apps and pipelines.

CORE-1534 Add admin app version endpoints

---

src/apps/service/apps/de/docs.clj
src/apps/service/apps/de/edit.clj
src/apps/service/apps/de/pipeline_edit.clj

This PR will update the app version creation endpoint (CORE-1510) and the pipeline creation endpoint (CORE-1756) to copy documentation from the previous version's documentation.

CORE-316 Update app version create endpoint to copy documentation

---

project.clj
src/apps/service/apps/de/listings.clj

Updated the `apps.service.apps.de.listings/format-app-pipeline-eligibility` function to no longer remove the `overall_job_type` field in app listing details.
This will allow the UI to label apps with the `interactive` job type as VICE apps.

CORE-1808 Return overall_job_type field in app listings and details

---

src/apps/persistence/jobs.clj

This was causing a PostgreSQL error when the ownership filter was included with any of the standard filters in a job listing request. The error no longer occurs after making the change:

CORE-1875: fixed the application ofthe ownership filter to job listings

---

src/apps/clients/async_tasks.clj
src/apps/service/apps/jobs/sharing.clj

The `get-user-from-subject` function is copied from terrain, and other than that it's just using it.
I still need to test this, but reviews are welcome as I do.

Enable sharing analysis inputs and outputs with groups

---

project.clj
src/apps/routes/schemas/tool.clj
src/apps/routes/tools.clj
src/apps/service/apps/de/listings.clj
src/apps/tools.clj
src/apps/tools/private.clj
src/apps/util/config.clj

Hopefully fairly easily understood. For the UI, we've added an include-defaults parameter (cyverse-de/common-swagger-api#84 and cyverse-de/terrain#277 for the schema and ensuring that reaches this service, resp.) so that when _editing_ tools the configured default isn't listed as though it's the tool-specific configured value. When launching apps, however, the default should show up seamlessly as though it's configured in the tool & passed down to app-exposer.
This still needs testing, but as discussed elsewhere I might do so in the QA environment to ease the cross-service setup process.

CORE-1971: manage default memory & CPU limits as configuration values in the apps service instead of hardcoded values in app-exposer

---

src/apps/metadata/tool_requests.clj
src/apps/service/integration_data.clj
src/apps/user.clj
src/apps/webhooks.clj

This tries to centralize the logic for username suffix handling to all use a regex-type approach like I used in the analyses service (remove everything starting from the first `@`, then add the suffix after that). This moves most places that cared about the configuration property to use the same function within apps.user, with one exception that was set up to pass the uid domain in. That could maybe go away too, but thought I'd get this much up at least.

Handle username suffix better

---

src/apps/service/apps/de/jobs/common.clj

Updated `apps.service.apps.de.jobs.common/reconcile-container-requirements` to use `0` for the max CPU request for user submissions if nothing was submitted from the client.
This will prevent the maximum CPUs set by the tool from being used in the final job submission, allowing the job services to use their own reasonable default instead (currently `4`).
A similar check was added for user `memory_limit` requests, which will also allow job services to use their own defaults (VICE jobs will use `8Gi`, for example).

CORE-2011 Update max CPU reconciliation in DE job submissions.

---

project.clj
src/apps/persistence/app_metadata.clj
src/apps/protocols.clj
src/apps/routes/apps.clj
src/apps/routes/apps/versions.clj
src/apps/service/apps.clj
src/apps/service/apps/agave.clj
src/apps/service/apps/combined.clj
src/apps/service/apps/de.clj
src/apps/service/apps/de/edit.clj

Added `PUT /apps/:system/:id/versions` for reordering app versions.
This endpoint expects the app versions to be in descending order, with the newest (or latest) first, since that is also the way they are listed in the app details and listing endpoints.

CORE-1955 Add endpoint for reordering app versions

---

src/apps/persistence/users.clj
src/apps/routes/schemas/user.clj
src/apps/routes/users.clj
src/apps/service/users.clj

This adds an endpoint that lists the most recent N (default 5) logins in the database for the logged-in user. After adding here, a passthrough will be added in terrain and a table to display this information in Sonora. As part of putting it in terrain or in advance of that, I may move some of the schemas to common-swagger-api, but it seemed like just doing it here to start was easier & would be easier to review.
Related: https://github.com/cyverse-de/terrain/pull/294

Logins endpoint

---

project.clj

`mvxcvi/clj-pgp` v1.1.1 was throwing exceptions while trying to decrypt Tapis access tokens, with messages like "invalid header encountered" or "Unexpected end of ZIP input stream", from org.bouncycastle.openpgp.PGPCompressedData.

Downgrade to mvxcvi/clj-pgp v1.1.0
