project.clj
src/apps/amqp.clj
src/apps/core.clj
src/apps/events.clj
src/apps/util/config.clj

Adds support for the AMQP ping event. Depends on https://github.com/cyverse-de/ansible/pull/8.

Add support for the ping event

---

src/apps/service/apps/de/listings.clj

This PR allows admins to restrict app searches to only public apps.

CORE-3949 Exclude non-public apps from admin app search results.

---

project.clj

This change is tiny, so I'm going to merge it immediately.

CORE-8516: updated one of the dependencies

---

src/apps/service/apps/de/validation.clj

Apps using private tools will now cause `GET /apps/:system-id/:app-id/is-publishable` to return false and `POST /apps/:system-id/:app-id/publish` to return an error.

CORE-8798 Add private tool validation to is-publishable and publish endpoints

---

src/apps/persistence/app_metadata.clj
src/apps/routes/tools.clj
src/apps/service/apps/de/listings.clj
src/apps/validation.clj

Adds endpoints for listing apps using a given tool.
The non-admin endpoint also checks if the requesting user has `read` permission for the given tool.

CORE-8814 Add GET (/admin)/tools/:tool-id/apps endpoints.

---

src/apps/persistence/app_groups.clj
src/apps/protocols.clj
src/apps/routes/admin.clj
src/apps/routes/schemas/app/category.clj
src/apps/service/apps.clj
src/apps/service/apps/agave.clj
src/apps/service/apps/combined.clj
src/apps/service/apps/de.clj
src/apps/service/apps/de/listings.clj

This is a new endpoint to search for app categories by name.

CORE-9052: add the ability to search for app categories by name

---

src/apps/containers.clj
src/apps/persistence/entities.clj
src/apps/persistence/tools.clj
src/apps/routes/schemas/containers.clj
src/apps/routes/schemas/tool.clj

Adds the `interactive` boolean field to the container settings map.
Adds the `interactive_apps` map to the container settings.
Adds the `container_ports` list to the container-settings.

Changes related to interactive apps

---

src/apps/constants.clj
src/apps/persistence/jobs.clj
src/apps/persistence/tools.clj
src/apps/service/apps/de.clj
src/apps/service/apps/de/jobs.clj

There's still some testing left to be done, but the testing will involve job submissions. It's probably easiest to merge the changes and test them in the development environment.

CORE-9244: add the OSG tool type, job type and system ID.

---

project.clj
src/apps/persistence/app_metadata.clj
src/apps/service/apps/de/edit.clj

This is the first of several related pull requests. I figured I'd submit a pull request for every functionality change to make them easier to review.

CORE-4632: added rule argument validations to app update endpoints

---

src/apps/routes/schemas/analysis/listing.clj
src/apps/service/apps/job_listings.clj

It _seems_ to work! I'm sure there are some clojure tricks and shortcuts I'm unaware of that could be utilized though 😄

CORE-9280 Add interactive URLs to the analysis listings

---

project.clj
src/apps/clients/iplant_groups.clj
src/apps/clients/metadata.clj
src/apps/routes.clj
src/apps/routes/apps/communities.clj
src/apps/service/apps/communities.clj

Adds endpoints for adding or removing only App Community tags for #124.

Add (/admin)/apps/{app-id}/communities endpoints.

---

src/apps/clients/notifications.clj
src/apps/service/apps/communities.clj
src/apps/service/apps/de/metadata.clj

This PR will update the `POST /apps/{system-id}/{app-id}/publish` endpoint to notify community admins when the app is tagged by the user with that community, for #128.

Notify community admins when app made public in that community

---

src/apps/tools/private.clj

This PR will allow private tool updates for OSG and Interactive tool types, and also set the network mode to "bridge" for interactive tools types.

Allow updates for private OSG and Interactive tool types.

---

src/apps/service/apps/de/metadata.clj
src/apps/service/apps/de/validation.clj
src/apps/util/config.clj

My biggest concern here is that there might be some more corner cases that I haven't thought of. If reviewers could keep this in mind while looking over the code, I'd appreciate it.

CORE-127: automatically publish tools when an app is being published

---

src/apps/routes.clj
src/apps/routes/admin.clj
src/apps/routes/admin/reference_genomes.clj
src/apps/routes/schemas/reference_genome.clj

This PR will replace the docs and schemas for `/admin/reference-genomes` endpoints with those added by cyverse-de/common-swagger-api#34.

CORE-11 Migrate docs and schemas for /admin/reference-genomes endpoints

---

project.clj
src/apps/service/apps/de/docs.clj
src/apps/service/apps/de/listings.clj

Includes update of common-swagger-api for cyverse-de/common-swagger-api#42

CORE-63: Add app documentation to admin app details where available

---

src/apps/clients/notifications.clj
src/apps/service/apps/de/listings.clj
src/apps/service/apps/de/metadata.clj

This PR contains two very small changes to fix some bugs that we found while testing app publication requests.
This PR should be merged after https://github.com/cyverse-de/apps/pull/193. I wanted these changes to go in a separate PR just for clarity.

Publication request fixes

---

project.clj

Must wait for https://github.com/cyverse-de/common-swagger-api/pull/62 to be merged

CORE-1148 Bump common-swagger-api version

---

project.clj
src/apps/clients/notifications.clj
src/apps/metadata/params.clj
src/apps/persistence/app_documentation.clj
src/apps/persistence/app_groups.clj
src/apps/persistence/app_listing.clj
src/apps/persistence/app_metadata.clj
src/apps/persistence/app_metadata/delete.clj
src/apps/persistence/app_metadata/relabel.clj
src/apps/persistence/app_search.clj
src/apps/persistence/entities.clj
src/apps/persistence/jobs.clj
src/apps/service/apps.clj
src/apps/service/apps/combined/util.clj
src/apps/service/apps/de/admin.clj
src/apps/service/apps/de/docs.clj
src/apps/service/apps/de/edit.clj
src/apps/service/apps/de/job_view.clj
src/apps/service/apps/de/jobs.clj
src/apps/service/apps/de/jobs/base.clj
src/apps/service/apps/de/jobs/common.clj
src/apps/service/apps/de/listings.clj
src/apps/service/apps/de/metadata.clj
src/apps/service/apps/de/pipeline_edit.clj
src/apps/service/apps/de/validation.clj
src/apps/service/apps/job_listings.clj
src/apps/service/apps/jobs.clj
src/apps/service/apps/jobs/params.clj
src/apps/service/apps/jobs/submissions.clj

This PR will update existing endpoints for compatibility with app versions db migrations.
This PR should not be merged until after cyverse-de/de-database#10 and cyverse-de/common-swagger-api#75 are merged.
This PR will update the following apps endpoints to use, update, create, and/or return info for the latest app version.
* `GET /apps`
* `POST /apps/{system-id}`
* `DELETE /apps/{system-id}/{app-id}`
* `GET /apps/{system-id}/{app-id}`
* `PATCH /apps/{system-id}/{app-id}`
* `PUT /apps/{system-id}/{app-id}`
* `POST /apps/{system-id}/{app-id}/copy`
* `GET /apps/{system-id}/{app-id}/listing`
* `GET /apps/{system-id}/{app-id}/details`
* `GET /apps/{system-id}/{app-id}/documentation`
* `PATCH /apps/{system-id}/{app-id}/documentation`
* `POST /apps/{system-id}/{app-id}/documentation`
* `GET …

CORE-316 Initial updates for app versions db migrations

---

src/apps/service/apps/de/admin.clj

App integrators are sent a notification when an app is deleted with the admin app `DELETE` endpoint, but an app can also be deleted with the `PATCH /admin/apps/:system-id/:app-id` endpoint.
This PR will update the `PATCH /admin/apps/:system-id/:app-id` endpoint to also send app deletion notifications to app integrators.

CORE-1803 Notify integrators of app deletion from admin PATCH endpoint

---

src/apps/service/apps/job_listings.clj

This is a pretty small fix for a user's dashboard stats, so I'm going to merge this right away, but reviews are still welcome 🙇

CORE-1875 Fix /analyses/stats endpoint response

---

src/apps/persistence/users.clj
src/apps/routes/schemas/user.clj
src/apps/routes/users.clj
src/apps/service/users.clj

combines with cyverse-de/terrain#292 and cyverse-de/de-database#28

Keycloak-based login tracking

---

src/apps/service/apps/de/jobs/common.clj
src/apps/service/apps/de/jobs/resources.clj
test/apps/service/apps/resources_test.clj

We were encountering a problem where the memory requests weren't being honored for VICE job submissions. This is an attempt to fix the problem.

CORE-2024: memory and cpu request limit fixes

---

project.clj
src/apps/routes/schemas/user.clj
src/apps/routes/users.clj

ref: cyverse-de/common-swagger-api#89

Use the common-swagger-api ListLoginsResponse
